# Generated by Django 5.2 on 2025-04-06 06:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abs_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_plate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SideItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abs_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_plate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MainItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abs_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_plate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('main_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.mainitem')),
                ('components', models.ManyToManyField(blank=True, related_name='main_items', to='sales.rawitem')),
            ],
        ),
        migrations.CreateModel(
            name='PlateSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_per_plate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sides', models.ManyToManyField(blank=True, related_name='plate_sales', to='sales.sideitem')),
            ],
        ),
    ]
