# Generated by Django 5.2 on 2025-04-06 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_mainitem_main_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainitem',
            old_name='abs_price',
            new_name='cost_price',
        ),
        migrations.RenameField(
            model_name='rawitem',
            old_name='abs_price',
            new_name='cost_price',
        ),
        migrations.RenameField(
            model_name='sideitem',
            old_name='abs_price',
            new_name='cost_price',
        ),
    ]
