# Generated by Django 5.2 on 2025-04-06 09:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawitem',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
