# Generated by Django 5.2 on 2025-04-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_rawitem_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.RemoveField(
            model_name='platesale',
            name='sides',
        ),
        migrations.DeleteModel(
            name='SideItem',
        ),
    ]
