# Generated by Django 5.2 on 2025-04-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_delete_expense_remove_platesale_sides_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawitem',
            name='price_per_plate',
        ),
        migrations.AlterField(
            model_name='platesale',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
