# Generated by Django 5.2 on 2025-04-06 11:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_remove_rawitem_price_per_plate_alter_platesale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platesale',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
