# Generated by Django 5.2 on 2025-04-06 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_platesale_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainitem',
            name='price_per_plate',
        ),
    ]
